-- Alumni roster seed — 276 rows from the committee's Class of '87 attendance sheet.
-- Run AFTER 20260721_alumni_roster.sql. Idempotent (ON CONFLICT DO NOTHING on the kelas+absen key).
-- ⚠️ NOT YET APPLIED to production.

INSERT INTO alumni_roster (kelas, absen, nama_lengkap, nama_update, status, rip) VALUES
  ('3A', 1, 'E. ADI NUGROHO', NULL, NULL, false),
  ('3A', 2, 'AGUS BUDHIJANTO', NULL, NULL, false),
  ('3A', 3, 'ANDI HEMAN WIDJAJANA', NULL, 'hadir', false),
  ('3A', 4, 'ARTHYA RUSTANDI', NULL, 'hadir', false),
  ('3A', 5, 'AUDY WIDJAJA', NULL, 'belum_isi', false),
  ('3A', 6, 'AUGUSTINUS FH HARDIMAN', NULL, NULL, false),
  ('3A', 7, 'BISMA STANIARTO', NULL, NULL, false),
  ('3A', 8, 'CHARLES UNSULANGI', NULL, NULL, false),
  ('3A', 9, 'DANNY SUARDI', NULL, 'hadir', false),
  ('3A', 10, 'DARWIN SALAMONY', NULL, NULL, false),
  ('3A', 11, 'EDI MULYADI', 'EDI MULJADI', 'hadir', false),
  ('3A', 12, 'EDUARD MULYONO', NULL, NULL, false),
  ('3A', 13, 'F.X SARI INDRAJANI L.', 'SARI INDRAJANI', 'hadir', false),
  ('3A', 14, 'HARYANTO YAHJA SAPUTRA', 'HARJANTO JAHJA SAPUTRA', 'hadir', false),
  ('3A', 15, 'HANRIKUS BAMBANG P.', 'BAMBANG POERWANTO', 'hadir', false),
  ('3A', 16, 'HENRY WINARTA', NULL, 'hadir', false),
  ('3A', 17, 'INDAH L.S.', NULL, NULL, false),
  ('3A', 18, 'JEAN SUTARJA', NULL, NULL, false),
  ('3A', 19, 'JOLAN', 'JOLAN TIO', 'hadir', false),
  ('3A', 20, 'JULIUS ABYASA', NULL, NULL, false),
  ('3A', 21, 'JOHANNES DWIARTANTO', NULL, 'hadir', false),
  ('3A', 22, 'KOKO GUNADI R.', NULL, NULL, false),
  ('3A', 23, 'LILY HERNAWAN', NULL, NULL, false),
  ('3A', 24, 'LIM HU YEN', NULL, NULL, false),
  ('3A', 25, 'LINDY RUSTANDI', NULL, 'hadir', false),
  ('3A', 26, 'LUCAS PRANA SUNARYA', NULL, 'hadir', false),
  ('3A', 27, 'MULJANA CHANDRA', 'MULJANA TJANDRA', 'belum_isi', false),
  ('3A', 28, 'NANI WINARNI', NULL, NULL, false),
  ('3A', 29, 'ONG JEN CHAU', NULL, 'hadir', false),
  ('3A', 30, 'RIANY HARSIDI', 'RIANY CLEMENT', 'hadir', false),
  ('3A', 31, 'ROSSY', NULL, NULL, false),
  ('3A', 32, 'SHINTA DEWI T.', NULL, NULL, false),
  ('3A', 33, 'SIGIT PRASETYA', NULL, NULL, false),
  ('3A', 34, 'SUNARTO', NULL, 'belum_isi', false),
  ('3A', 35, 'SUSAN LIMIAWATI H.', NULL, NULL, false),
  ('3A', 36, 'THEN TJUNG HIAN', NULL, NULL, false),
  ('3A', 37, 'THOMAS TEGUH S.', NULL, NULL, false),
  ('3A', 38, 'UUNG TJAHJAPUTRA', 'FLORENTINA UUNG TJAHJAPUTRA', 'hadir', false),
  ('3A', 39, 'WIDIA BUDHI SUSETYO', NULL, NULL, false),
  ('3A', 41, 'YENY RAHMAJANY', NULL, NULL, false),
  ('3A', 42, 'ZAKI FIRMANSYAH', 'ZAKI FIRMANSJAH', 'hadir', false),
  ('3A', 43, 'WIWI KURNIADI YAHYA', NULL, 'hadir', false),
  ('3B', 1, 'AGUS BUDHYHARTONO', 'YAN B. BUDHYHARTONO', 'hadir', false),
  ('3B', 2, 'ANDRE HENDARMAN', NULL, 'hadir', false),
  ('3B', 3, 'ANDY H. (ANTON)', 'ANDY HALIM', 'hadir', false),
  ('3B', 4, 'BONIFACUS BUDI P.', NULL, NULL, false),
  ('3B', 5, 'BONTOR SAUT TUA PANGGABEAN', 'BONTOR PANGGABEAN', 'hadir', false),
  ('3B', 6, 'BUDI SETIAWAN', NULL, NULL, true),
  ('3B', 7, 'CHRISTIANTI G. TIJONO', NULL, NULL, false),
  ('3B', 8, 'DAVID ADHITYO D.', NULL, 'belum_isi', false),
  ('3B', 9, 'DENI DANIEL', NULL, NULL, false),
  ('3B', 10, 'EMANUEL TIMOTIUS', 'EMMANUEL TIMOTIUS', 'hadir', false),
  ('3B', 11, 'EVY KARTIKA DEWI', NULL, NULL, false),
  ('3B', 12, 'FEBRIAN TEGUH', 'FEBRIAN TEGUH KARYADI', 'hadir', false),
  ('3B', 13, 'TOMMY ATMADJA', NULL, NULL, false),
  ('3B', 14, 'HERIADI PRIAMBODO', 'HERIADI JOEWONO', 'belum_tahu', false),
  ('3B', 15, 'HERJANTI WIDJAJA', 'HERJANTY WIDJAJA', 'hadir', false),
  ('3B', 16, 'INDRIANI', NULL, NULL, false),
  ('3B', 17, 'JULIUS STEPHANDI', NULL, NULL, false),
  ('3B', 18, 'KHOE ING SEN', 'SENDARIUS LESMANA', 'hadir', false),
  ('3B', 19, 'KWET PHIAO', 'KWET PHIAO TJAKRASENDJAJA', 'hadir', false),
  ('3B', 20, 'LENNY GUNADI', 'LENNY GUNADI LEMAN', 'hadir', false),
  ('3B', 21, 'LEO SUTHA', NULL, 'hadir', false),
  ('3B', 22, 'PAOLI', NULL, NULL, false),
  ('3B', 23, 'LIEM KONG SHIUNG', NULL, 'hadir', false),
  ('3B', 24, 'LILY KURNIADI', 'LILI KURNIADI', 'hadir', false),
  ('3B', 25, 'LUCIA C.', NULL, NULL, false),
  ('3B', 26, 'MULJANA PAULUS', 'MULJANA SONDJAJA', 'hadir', false),
  ('3B', 27, 'ONG SIUSIN', NULL, NULL, false),
  ('3B', 28, 'RACHMAT', NULL, NULL, false),
  ('3B', 29, 'RINA PRAMITA E.', 'RINA PRAMITA EFENDI', 'hadir', false),
  ('3B', 30, 'ROSALINA HALIM', NULL, NULL, false),
  ('3B', 31, 'RUDY DARMA', NULL, 'hadir', false),
  ('3B', 32, 'SIU MING S', 'CYNTHIA SAPUTRA', 'hadir', false),
  ('3B', 33, 'SUSANA SALIM', NULL, 'hadir', false),
  ('3B', 34, 'SYLVIA KAMADJAJA', NULL, 'belum_tahu', false),
  ('3B', 35, 'SEPTIMIUS IRWAN D.', 'SEPTIMIUS IRWAN DJOHANSJAH', 'hadir', false),
  ('3B', 36, 'TAN SIU IYEN', NULL, NULL, false),
  ('3B', 37, 'TJIANG HUE (WINARTA)', NULL, NULL, false),
  ('3B', 38, 'TENACIOUS NIRWANSYAH T.', 'TENACIOUS THOMAS', 'hadir', false),
  ('3B', 39, 'THE MAZMUR', NULL, NULL, false),
  ('3B', 40, 'HERYANTO (Tjiong Hung Fu)', 'HERYANTO TJIONG', 'hadir', false),
  ('3B', 41, 'T. TJEN TJUNG', NULL, NULL, false),
  ('3B', 42, 'VERONICA SUSANTI', NULL, NULL, false),
  ('3B', 43, 'WILLIAM P.', NULL, NULL, false),
  ('3B', 44, 'YOHANES DARMAWAN EDY', NULL, NULL, false),
  ('3B', 45, 'IWAN TUNGGAWIDJAJA', NULL, 'hadir', false),
  ('3C', 1, 'ANASTASIA MEDIANA', NULL, NULL, false),
  ('3C', 2, 'ANTONIUS DJALU S', NULL, NULL, false),
  ('3C', 3, 'B. EDDY LUCKY', NULL, 'hadir', false),
  ('3C', 4, 'BOLO DWIARTOMO', NULL, 'hadir', false),
  ('3C', 5, 'CHRISTIE KUSNANDAR', NULL, NULL, false),
  ('3C', 6, 'DADAN MULYAWAN', NULL, NULL, false),
  ('3C', 7, 'DANIEL LM', NULL, NULL, false),
  ('3C', 8, 'DEWI YANTI', NULL, NULL, false),
  ('3C', 9, 'ERWIN B. ADHIWIJAYA', 'ERWIN ADHIWIJAYA', 'hadir', false),
  ('3C', 10, 'FENDI RUSMANA', NULL, 'hadir', false),
  ('3C', 11, 'FRANCISCUS LEO LUMME', NULL, NULL, false),
  ('3C', 12, 'FREDY DISASTRA', NULL, 'hadir', false),
  ('3C', 13, 'GANDA LESMANA', NULL, 'hadir', false),
  ('3C', 14, 'HARTONO RIANTO', NULL, NULL, false),
  ('3C', 15, 'HENDARMIN RUSTANDI', 'HENDARMIN RUSTANDI SARSONO', 'hadir', false),
  ('3C', 16, 'HENDRA HARNOKO', NULL, 'hadir', false),
  ('3C', 17, 'HENDY MARTONO', NULL, NULL, false),
  ('3C', 18, 'HENRI MARINUS', NULL, NULL, false),
  ('3C', 19, 'HERLINA SURYA', NULL, NULL, false),
  ('3C', 20, 'HOUW TJOEI ING', 'VIRIANY', 'hadir', false),
  ('3C', 21, 'AGUS PURNAWAN P', NULL, 'hadir', false),
  ('3C', 22, 'IGN. S. HAMDANI', 'HAMDANI TJIPTA', 'hadir', false),
  ('3C', 23, 'INGRID VIVIANTI SANTOSA', NULL, NULL, false),
  ('3C', 24, 'INNIGO W.S.', 'INNICO SJAHANDI', 'hadir', false),
  ('3C', 25, 'IVY ISKANDAR', NULL, NULL, false),
  ('3C', 26, 'JAMES LINCOLN STIADY', NULL, 'hadir', false),
  ('3C', 27, 'JUDY WAROUW', NULL, NULL, false),
  ('3C', 28, 'LILY SUHENI SAPUTRA', 'LILY SAPUTRA', 'hadir', false),
  ('3C', 29, 'LUCY ARIANTY', 'LUCIA GUNAWAN', 'hadir', false),
  ('3C', 30, 'MARIUS R.', NULL, NULL, false),
  ('3C', 31, 'MARLINAWATI P.', 'MARLINAWATI PRADEWI', 'hadir', false),
  ('3C', 32, 'PAULUS GUNAWAN T.', 'PAUL TANUSUBROTO', 'hadir', false),
  ('3C', 33, 'QUENNY HENDAYANI', NULL, NULL, false),
  ('3C', 34, 'RAMLAN HANDOKO', NULL, NULL, false),
  ('3C', 35, 'RATNA SIDHARTA', 'NADYA SIDDHARTA', 'hadir', false),
  ('3C', 36, 'RIVAN', 'RIVAN MULYAWAN', 'hadir', false),
  ('3C', 37, 'RUDY P.', 'RUDY POERWO', 'hadir', false),
  ('3C', 38, 'SEBASTIAN ARIO SOBO', NULL, NULL, false),
  ('3C', 39, 'SISCA OKTAVIANA TASIRAN', NULL, NULL, false),
  ('3C', 40, 'SUWITHO THOMAS', NULL, NULL, true),
  ('3C', 41, 'TEDY SUGIARTO', NULL, NULL, false),
  ('3C', 42, 'TONY KUSNANDAR', 'TONI KUSNANDAR', 'hadir', false),
  ('3C', 43, 'YENNY SETIAWAN', NULL, NULL, false),
  ('3C', 44, 'JOHANES SUPRIHADI', NULL, NULL, false),
  ('3C', 45, 'LARRY SUTIKNO', NULL, 'belum_isi', false),
  ('3D', 1, 'ALOYSIUS SANTOSA', NULL, NULL, false),
  ('3D', 2, 'AMI JULIANTI', NULL, NULL, false),
  ('3D', 3, 'ANDREAS TEDY', 'ANDREAS TEDY MULYONO', 'hadir', false),
  ('3D', 4, 'BONITA PRAWIRODIHARDJO', NULL, 'belum_tahu', false),
  ('3D', 5, 'CATANIA AMBAR G.H.', NULL, NULL, false),
  ('3D', 6, 'CHRISTINA BOEDIARTO', NULL, 'hadir', false),
  ('3D', 7, 'CYNTHIA KRISTIADJI', NULL, NULL, false),
  ('3D', 8, 'DEWI FADJAR SURJANTO', NULL, NULL, true),
  ('3D', 9, 'DJUWITA ISKANDAR', NULL, 'hadir', false),
  ('3D', 10, 'ERNY HERYAWATI SUTANTO', NULL, 'hadir', false),
  ('3D', 11, 'FAN HWA SUN', NULL, NULL, false),
  ('3D', 12, 'FENTY LESTARI SUNARJO', NULL, 'hadir', false),
  ('3D', 13, 'GERARDUS DJUDJU KUSUMO', NULL, NULL, false),
  ('3D', 14, 'HADI SASTRA', NULL, NULL, false),
  ('3D', 15, 'HADI TJANDRA T.', 'HADY TJANDRA TJIPTAHARDJA', 'hadir', false),
  ('3D', 16, 'HENDRA SETIAWAN T.', NULL, 'hadir', false),
  ('3D', 17, 'HERMAN JOSEPH M.', NULL, 'belum_tahu', false),
  ('3D', 18, 'INGE R.D. DARMASETIAWAN', NULL, 'hadir', false),
  ('3D', 19, 'JANTO SLAMET', NULL, NULL, true),
  ('3D', 20, 'JENIE ARYANTI', 'JENIE ADISESHA', 'hadir', false),
  ('3D', 21, 'JIE KIAO LING', NULL, 'hadir', false),
  ('3D', 22, 'KRISTINA', NULL, 'hadir', false),
  ('3D', 23, 'LANAWATY', NULL, NULL, false),
  ('3D', 24, 'LANNY TEDJOKUSUMO', NULL, 'hadir', false),
  ('3D', 25, 'LAURA SITOMPUL', NULL, NULL, false),
  ('3D', 26, 'LELI ERIKA', NULL, 'hadir', false),
  ('3D', 27, 'LIANITA', NULL, NULL, false),
  ('3D', 28, 'LIM ZHI GING', 'IVAN TANARDI', 'hadir', false),
  ('3D', 29, 'LINDA TANUMIHARDJA', NULL, NULL, false),
  ('3D', 30, 'LUCIA WIRIAPRANATA', NULL, 'hadir', false),
  ('3D', 31, 'MARIA ELIZABETH R.R.', 'ROSALINA RIDWAN', 'hadir', false),
  ('3D', 32, 'MARIA HIASINTA FARIDA', 'MARIA HIASINTA', 'hadir', false),
  ('3D', 33, 'MARIETTA SHANTI', 'MARIETTA SHANTI PRANANTA', 'hadir', false),
  ('3D', 34, 'MEILYWATI', 'MEILYWATI WILLASTRA', 'hadir', false),
  ('3D', 35, 'MINARLI RIDWAN', NULL, NULL, false),
  ('3D', 36, 'NATASYAH TJIA SAU FU', NULL, NULL, false),
  ('3D', 37, 'PAUL', NULL, NULL, false),
  ('3D', 38, 'PENI SURYANI', NULL, 'hadir', false),
  ('3D', 39, 'RATNADEWI', NULL, NULL, false),
  ('3D', 40, 'RIDWAN TJANDRADJAJA', NULL, NULL, false),
  ('3D', 41, 'SANDRA B. SAMUEL', NULL, NULL, false),
  ('3D', 42, 'SASMOKO ADISANTOSO', NULL, NULL, false),
  ('3D', 43, 'SHI GWAT ING JOYCE', NULL, NULL, false),
  ('3D', 44, 'SU FEN', 'LAURENTIA SU FEN', 'hadir', false),
  ('3D', 45, 'LEONARDUS SURYAMAN YAHYA', 'SURJAMAN JAHJA', 'hadir', false),
  ('3D', 46, 'TAN HOAT LIANG', NULL, NULL, false),
  ('3D', 47, 'THE ANDREAS ANDI', 'ANDREAS ANDI SIDHARTA', 'hadir', false),
  ('3D', 48, 'WAHYUDI HARSONO', NULL, NULL, false),
  ('3D', 49, 'WINARYO RIDWAN', 'WINARJO RIDWAN', 'hadir', false),
  ('3D', 50, 'YESAYA', NULL, NULL, false),
  ('3E', 1, 'ALBERTUS PURWANTO', NULL, NULL, true),
  ('3E', 2, 'ANIES LASTIATI', NULL, NULL, false),
  ('3E', 3, 'ARYANI H.', NULL, NULL, false),
  ('3E', 4, 'BERNADETHA LILIAWATY', NULL, NULL, false),
  ('3E', 5, 'C.M. JANUAR SOESANTO', NULL, NULL, true),
  ('3E', 6, 'CHRISTINA CHANDRAWIGUNA', 'CHRISTINA CHANDRA', 'hadir', false),
  ('3E', 7, 'EMILIA RANTIAMA', 'EMILIA PASARIBU', 'hadir', false),
  ('3E', 8, 'ENDRO PRIOSAMUDRO', NULL, NULL, false),
  ('3E', 9, 'FERA ARIFIN', NULL, 'hadir', false),
  ('3E', 10, 'DIONICEA HANNY S.', NULL, NULL, false),
  ('3E', 11, 'HARIJANTO JOSWARA', NULL, 'hadir', false),
  ('3E', 12, 'HENDRA LIMANDJAJA', NULL, NULL, false),
  ('3E', 13, 'HERRY GUNADI', NULL, NULL, false),
  ('3E', 14, 'REZA LINGGA', NULL, NULL, true),
  ('3E', 15, 'IKE TJANDRADINATA', NULL, 'hadir', false),
  ('3E', 16, 'JACOB F. PATTIWAEL', 'JOPIE', NULL, true),
  ('3E', 17, 'JENNY GEERTRUIDA E.S.', NULL, NULL, false),
  ('3E', 18, 'JERRY MULYADI', NULL, NULL, false),
  ('3E', 19, 'MHG JHYS HENNI SRIWATI', 'HENNI LIANG', 'hadir', false),
  ('3E', 20, 'ML JULIA PUSPASARI', NULL, NULL, false),
  ('3E', 21, 'KARADI HANAM', NULL, 'hadir', false),
  ('3E', 22, 'LENNA', NULL, NULL, false),
  ('3E', 23, 'LILY SURJONO', NULL, NULL, false),
  ('3E', 24, 'LINA GUNAWAN', NULL, NULL, false),
  ('3E', 25, 'SUHARTINI DHARMANATA', NULL, NULL, false),
  ('3E', 26, 'LUKMAN C.', 'LUKMAN CAHYAWIJAYA', 'hadir', false),
  ('3E', 27, 'METTY MELAWATI', NULL, NULL, false),
  ('3E', 28, 'NANCY C. THYMA', NULL, NULL, false),
  ('3E', 29, 'NICO', NULL, 'belum_tahu', false),
  ('3E', 30, 'PRAJNA SANTI B', NULL, NULL, false),
  ('3E', 31, 'PRILANTINA P. PRISCILLA', NULL, NULL, true),
  ('3E', 32, 'RATNAWATY IRAWAN', NULL, NULL, false),
  ('3E', 33, 'RICKY ISKANDAR', NULL, 'hadir', false),
  ('3E', 34, 'R. ROBBY KURNIAWAN T.', NULL, NULL, false),
  ('3E', 35, 'ROCHAJATI', NULL, NULL, true),
  ('3E', 36, 'RUSLIM LIMIWIDJAJA', NULL, NULL, false),
  ('3E', 37, 'FA SAPTOADJI ARIBOWO', NULL, NULL, false),
  ('3E', 38, 'SOENARDI KUSUMO K.', 'NYONYO', NULL, true),
  ('3E', 39, 'SRI MULIAJATI', 'SRI WIRIAATMADJA', 'hadir', false),
  ('3E', 40, 'SUCY MULYADI', NULL, NULL, false),
  ('3E', 41, 'TH. TING HWEE LIAN', 'THEODORA LILIAN GIOVANI TANU', 'hadir', false),
  ('3E', 42, 'WIDYANA S. HARDJANI', NULL, NULL, false),
  ('3E', 43, 'WIWING ISNATA', NULL, NULL, false),
  ('3E', 44, 'YANTY GODJALI', NULL, NULL, false),
  ('3E', 45, 'YENNY SONTANI', NULL, NULL, true),
  ('3E', 46, 'YETTY R.', NULL, NULL, false),
  ('3E', 47, 'ZANNY', NULL, 'hadir', false),
  ('3E', 48, 'FERYANTI SETIAWAN', NULL, 'hadir', false),
  ('3F', 1, 'ALFONSUS TJAHJADI', NULL, 'hadir', false),
  ('3F', 2, 'A. SRI PRACAYANTI', NULL, NULL, false),
  ('3F', 3, 'ANDREAS BUDI RACHMAT', NULL, NULL, false),
  ('3F', 4, 'ASWIN GUNADI', NULL, 'hadir', false),
  ('3F', 5, 'BANGKIT STEFANUS', NULL, NULL, false),
  ('3F', 6, 'CHRISTINA JULIANA', NULL, NULL, false),
  ('3F', 7, 'DIAH PRAMESTI ROSA', 'DYAH PRAMESTI ROSA', 'hadir', false),
  ('3F', 8, 'ELINAWATI SUTANTO', 'ELINA SUTANTO', 'hadir', false),
  ('3F', 9, 'ELVY LUCIANA THEN', NULL, NULL, false),
  ('3F', 10, 'ERLIS SUTRISNO', NULL, 'hadir', false),
  ('3F', 11, 'EVA MARTONO', NULL, NULL, false),
  ('3F', 12, 'FANNY TJAHJANA', NULL, 'hadir', false),
  ('3F', 13, 'FRIDA WINATA', NULL, 'hadir', false),
  ('3F', 14, 'F.X. ALEX SIANTAN', NULL, 'hadir', false),
  ('3F', 15, 'IGN. S. BUDI SATRIO', NULL, NULL, false),
  ('3F', 16, 'IRAWAN ISKANDAR', NULL, NULL, false),
  ('3F', 17, 'JEFFREY B. VILLANUEVA', NULL, 'hadir', false),
  ('3F', 18, 'JULIA YANI', 'JULIA DILLON', 'belum_tahu', false),
  ('3F', 19, 'KHO EYKE MARYATI', 'EYKE MARJATI', 'hadir', false),
  ('3F', 20, 'LAUW HOUW MEI', NULL, NULL, false),
  ('3F', 21, 'LAUW LUKMAN HENDIK', NULL, 'hadir', false),
  ('3F', 22, 'LILY SALIM', NULL, NULL, false),
  ('3F', 23, 'LIM SIOE TJOE', NULL, NULL, false),
  ('3F', 24, 'MARIA B. MEITY', NULL, NULL, false),
  ('3F', 25, 'MELINDA HALIM', NULL, NULL, false),
  ('3F', 26, 'MONICA HENY L. D.', NULL, NULL, false),
  ('3F', 27, 'NATALIA NANIK', NULL, NULL, false),
  ('3F', 28, 'NIRBANAWATI', 'AGATHA MEY NIRBANAWATI', 'hadir', false),
  ('3F', 29, 'NURUL SULISTYANI', NULL, NULL, false),
  ('3F', 30, 'RIDWAN CAHYAWIJAYA', NULL, 'hadir', false),
  ('3F', 31, 'RUBIONO HARSADI', NULL, NULL, false),
  ('3F', 32, 'R.M. POLLY SULISTYA', NULL, NULL, true),
  ('3F', 33, 'SESILIA ONG A YOENG', NULL, NULL, false),
  ('3F', 34, 'SIANY PANGESTU', NULL, 'hadir', false),
  ('3F', 35, 'T.SRI SAFRINA WIRAWAN', NULL, NULL, false),
  ('3F', 36, 'SRIMEI ANDAJANI HUSEN', NULL, NULL, false),
  ('3F', 37, 'SUHERMAN AGUS', NULL, NULL, true),
  ('3F', 38, 'SUTJI DIANINGTYAS', NULL, NULL, false),
  ('3F', 39, 'TEDDY SANTOSO', NULL, NULL, false),
  ('3F', 40, 'TJHEN NJOEN JIN', NULL, NULL, false),
  ('3F', 41, 'TINA MARIANA TANU', NULL, NULL, false),
  ('3F', 42, 'TONO YOSHUA RAY', NULL, NULL, false),
  ('3F', 43, 'UUNG MIDJAJA', NULL, 'hadir', false),
  ('3F', 44, 'YANNY SUGIRI', 'YANNY JOANA', 'hadir', false),
  ('3F', 45, 'YOESMAN SUGIANTO', NULL, NULL, false),
  ('3F', 46, 'YULIANA MAWENGKANG', NULL, NULL, false)
ON CONFLICT (kelas, absen) DO NOTHING;
